import banana from "../assets/icons/banana.png";

export const categories = ["fruit", "vegetable"];

export const fruits = [
  "Apple",
  "Avocado",
  "Blueberry",
  "Cherry",
  "Fig",
  "Grape",
  "Kiwi",
  "Lemon",
  "Lime",
  "Nectarine",
  "Orange",
  "Peach",
  "Pear",
  "Plum",
  "Raspberry",
  "Strawberry",
  "Tangerine",
  "Date",
  "Pomegranate",
  "Persimmon",
  "Banana",

  // { name: "Apple", icon: banana },
  // { name: "Avocado", icon: banana },
  // { name: "Blueberry", icon: banana },
  // { name: "Cherry", icon: banana },
  // { name: "Fig", icon: banana },
  // { name: "Grape", icon: banana },
  // { name: "Kiwi", icon: banana },
  // { name: "Lemon", icon: banana },
  // { name: "Lime", icon: banana },
  // { name: "Nectarine", icon: banana },
  // { name: "Orange", icon: banana },
  // { name: "Peach", icon: banana },
  // { name: "Pear", icon: banana },
  // { name: "Plum", icon: banana },
  // { name: "Raspberry", icon: banana },
  // { name: "Strawberry", icon: banana },
  // { name: "Tangerine", icon: banana },
  // { name: "Date", icon: banana },
  // { name: "Pomegranate", icon: banana },
  // { name: "Persimmon", icon: banana },
  // { name: "Banana", icon: banana },
];

export const veggies = [
  "Asparagus",
  "Artichoke",
  "Broccoli",
  "Brussels sprouts",
  "Cabbage",
  "Carrot",
  "Celery",
  "Cucumber",
  "Garlic",
  "Green bean",
  "Lettuce",
  "Onion",
  "Pepper",
  "Potato",
  "Spinach",
  "Squash",
  "Tomato",
  "Zucchini",
  "Corn",
  "Eggplant",
];
